# Generated by Django 4.2.8 on 2023-12-29 17:23

import Profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('age', models.SmallIntegerField(blank=True, default=10, null=True, verbose_name='age')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('phon_number', models.CharField(blank=True, max_length=13, null=True, validators=[Profile.validators.IranianMobileNumberValidator()], verbose_name='Mobile Number')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
            ],
        ),
    ]
