# Generated by Django 4.2.8 on 2023-12-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='points',
        ),
    ]
