# Generated by Django 5.0 on 2023-12-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediamodel_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='my_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
