# Generated by Django 4.2.8 on 2023-12-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediamodel_image_alter_mediamodel_my_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediamodel',
            name='my_file',
        ),
    ]
