# Generated by Django 5.0 on 2023-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('start_release_date', models.DateField(blank=True, null=True, verbose_name='start_release')),
                ('end_release_date', models.DateField(blank=True, null=True, verbose_name='end_release')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
    ]
