# Generated by Django 5.0 on 2023-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='runtime'),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('anime', 'Anime'), ('tv_series', 'Tv Series')], default='movie', max_length=20),
        ),
    ]
