# Generated by Django 5.0 on 2023-12-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_episodes_movie_imdb_rating_movie_runtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
    ]
