# Generated by Django 4.2.8 on 2023-12-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_movie_episodes_movie_imdb_rating_movie_runtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casts',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(related_name='cast_movies', to='movies.casts'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_movie', to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='director_movies', to='movies.genre'),
        ),
    ]
