# Generated by Django 4.2.8 on 2023-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_casts_movies_remove_director_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casts',
            old_name='name',
            new_name='cast_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='director_name',
        ),
    ]
