# Generated by Django 4.2.8 on 2023-12-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_name_casts_cast_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
